spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  batch:
    job:
      enabled: fals # we will enable job from rest api so setting this to false
    jdbc:
      initialize-schema: always


